### ISSUE TITLE
Fehler Code : 42000 bei 5.2.4  Imprort Adressen von XTC 3.0.4

### ISSUE THREAD

**Issue by mbdesign** [shopwareLabs/SwagMigration#11]
Beim Importieren der Kunden ist ein Fehler aufgetreten

Code : 42000
Line : 234
File : /home/mbdesign/public_html/shopware/engine/Library/Zend/Db/Statement/Pdo.php

Error : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '@mb-design.de)' at line 2
Trace : #0 /home/mbdesign/public_html/shopware/engine/Library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array) #1 /home/mbdesign/public_html/shopware/engine/Library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array) #2 /home/mbdesign/public_html/shopware/engine/Library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO s_c...', Array) #3 /home/mbdesign/public_html/shopware/engine/Library/Enlight/Components/Db/Adapter/Pdo/Mysql.php(96): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO s_c...', Array) #4 /home/mbdesign/public_html/shopware/engine/Shopware/Plugins/Community/Backend/SwagMigration/Components/DbServices/Import/CustomerImporter.php(780): Enlight_Components_Db_Adapter_Pdo_Mysql->query('INSERT INTO s_c...') #5 /home/mbdesign/public_html/shopware/engine/Shopware/Plugins/Community/Backend/SwagMigration/Components/DbServices/Import/CustomerImporter.php(290): Shopware\SwagMigration\Components\DbServices\Import\CustomerImporter->newsletterSubscribe(Array) #6 /home/mbdesign/public_html/shopware/engine/Shopware/Plugins/Community/Backend/SwagMigration/Components/DbServices/Import/Import.php(229): Shopware\SwagMigration\Components\DbServices\Import\CustomerImporter->import(Array) #7 /home/mbdesign/public_html/shopware/engine/Shopware/Plugins/Community/Backend/SwagMigration/Components/Migration/Import/Resource/Customer.php(165): Shopware\SwagMigration\Components\DbServices\Import\Import->customer(Array) #8 /home/mbdesign/public_html/shopware/engine/Shopware/Plugins/Community/Backend/SwagMigration/Components/Migration/Import/Resource/Customer.php(77): Shopware\SwagMigration\Components\Migration\Import\Resource\Customer->migrateCustomer(Array, Object(Shopware\SwagMigration\Components\DbServices\Import\Import), '') #9 /home/mbdesign/public_html/shopware/engine/Shopware/Plugins/Community/Backend/SwagMigration/Controllers/Backend/SwagMigration.php(465): Shopware\SwagMigration\Components\Migration\Import\Resource\Customer->run() #10 /home/mbdesign/public_html/shopware/engine/Shopware/Plugins/Community/Backend/SwagMigration/Controllers/Backend/SwagMigration.php(502): Shopware_Controllers_Backend_SwagMigration->runImport('import_customer...') #11 /home/mbdesign/public_html/shopware/engine/Library/Enlight/Controller/Action.php(159): Shopware_Controllers_Backend_SwagMigration->importAction() #12 /home/mbdesign/public_html/shopware/engine/Library/Enlight/Controller/Dispatcher/Default.php(523): Enlight_Controller_Action->dispatch('importAction') #13 /home/mbdesign/public_html/shopware/engine/Library/Enlight/Controller/Front.php(223): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp)) #14 /home/mbdesign/public_html/shopware/engine/Shopware/Kernel.php(176): Enlight_Controller_Front->dispatch() #15 /home/mbdesign/public_html/shopware/vendor/symfony/http-kernel/HttpCache/HttpCache.php(487): Shopware\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #16 /home/mbdesign/public_html/shopware/engine/Shopware/Components/HttpCache/AppCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), tr

**Comment by mitelg** [comment]
Hi @mbdesign 
we will release a new version of SwagMigration today. this issue should no longer exist here. 
If the issue still occurs, please use our [Issue Tracker](https://issues.shopware.com/) to report the bug :+1: 
best regards
Michael Telgmann

**Comment by smhhwps** [comment]
Hallo,
heute, am 30.08.2016 Version 5.2.5 gleicher fehler bei Importversuch.

Beim Importieren der Kunden ist ein Fehler aufgetreten

Code : 42000
Line : 234
File : /html/shopware/engine/Library/Zend/Db/Statement/Pdo.php

Error : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@namepromotion.de)' at line 2
Trace : #0 /html/shopware/engine/Library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array) #1 /html/shopware/engine/Library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array) #2 /html/shopware/engine/Library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO s_c...', Array) #3 /html/shopware/engine/Library/Enlight/Components/Db/Adapter/Pdo/Mysql.php(96): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO s_c...', Array) #4 /html/shopware/engine/Shopware/Plugins/Community/Backend/SwagMigration/Components/DbServices/Import/CustomerImporter.php(787): Enlight_Components_Db_Adapter_Pdo_Mysql->query('INSERT INTO s_c...') #5 /html/shopware/engine/Shopware/Plugins/Community/Backend/SwagMigration/Components/DbServices/Import/CustomerImporter.php(293): Shopware\SwagMigration\Components\DbServices\Import\CustomerImporter->newsletterSubscribe(Array) #6 /html/shopware/engine/Shopware/Plugins/Community/Backend/SwagMigration/Components/DbServices/Import/Import.php(229): Shopware\SwagMigration\Components\DbServices\Import\CustomerImporter->import(Array) #7 /html/shopware/engine/Shopware/Plugins/Community/Backend/SwagMigration/Components/Migration/Import/Resource/Customer.php(165): Shopware\SwagMigration\Components\DbServices\Import\Import->customer(Array) #8 /html/shopware/engine/Shopware/Plugins/Community/Backend/SwagMigration/Components/Migration/Import/Resource/Customer.php(77): Shopware\SwagMigration\Components\Migration\Import\Resource\Customer->migrateCustomer(Array, Object(Shopware\SwagMigration\Components\DbServices\Import\Import), '') #9 /html/shopware/engine/Shopware/Plugins/Community/Backend/SwagMigration/Controllers/Backend/SwagMigration.php(465): Shopware\SwagMigration\Components\Migration\Import\Resource\Customer->run() #10 /html/shopware/engine/Shopware/Plugins/Community/Backend/SwagMigration/Controllers/Backend/SwagMigration.php(502): Shopware_Controllers_Backend_SwagMigration->runImport('import_customer...') #11 /html/shopware/engine/Library/Enlight/Controller/Action.php(159): Shopware_Controllers_Backend_SwagMigration->importAction() #12 /html/shopware/engine/Library/Enlight/Controller/Dispatcher/Default.php(523): Enlight_Controller_Action->dispatch('importAction') #13 /html/shopware/engine/Library/Enlight/Controller/Front.php(223): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp)) #14 /html/shopware/engine/Shopware/Kernel.php(176): Enlight_Controller_Front->dispatch() #15 /html/shopware/vendor/symfony/http-kernel/HttpCache/HttpCache.php(487): Shopware\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #16 /html/shopware/engine/Shopware/Components/HttpCache/AppCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true, NULL) #17 /html/shopware/vendor/symfony/http-kernel/HttpCache/HttpCache.php(258): Shopware\Components\HttpCache\AppCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #18 /html/shopware/engine/Shopware/Components/HttpCache/AppCache.php(103): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #19 /html/shopware/shopware.php(101): Shopware\Components\HttpCache\AppCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #20 {main}
