### ISSUE TITLE
Kundennummer bei XtCommerce.php  customers_cid statt customers_id

### ISSUE THREAD

**Issue by mbdesign** [shopwareLabs/SwagMigration#12]
in der Datei SwagMigration/Components/Migration/Profile/XtCommerce.php  sollte besser    customers_cid  als customernumber verwendet werden.

u.customers_id 	 as customernumber,

ändern in

u.customers_cid 	 as customernumber,

**Comment by mitelg** [comment]
Hi @mbdesign 
in https://github.com/shopwareLabs/SwagMigration/blob/master/Components/DbServices/Import/CustomerImporter.php#L742 a new Shopware customer number is generated. So it doesn't matter what is selected from the original database.
Best regards
Michael Telgmann

**Comment by mbdesign** [comment]
Hi Michael,

thank you!

I know but if you use a Connector to aERP System you need to migrate alos the old customer ID.

**Comment by mitelg** [comment]
Hi @mbdesign 
even if it would be changed, the customernumber is never saved anywhere. How do you want to use it then?
Best regards
Michael Telgmann
