### ISSUE TITLE
Standard Liefer und Rechnungsanschrift wir nicht gesetzt

### ISSUE THREAD

**Issue by mbdesign** [shopwareLabs/SwagMigration#13]
default_billing_address_id 

und 

default_shipping_address_id

wird nicht gefüllt

Customerimporter.php   copy und paste Fehler bei 

'salutation' => $customer['shipping_company'],

**Comment by mitelg** [comment]
Hi @mbdesign 
we will release a new version of SwagMigration today. this issue should no longer exist here. 
If the issue still occurs, please use our [Issue Tracker](https://issues.shopware.com/) to report the bug :+1: 
best regards
Michael Telgmann

**Comment by mbdesign** [comment]
Ok i will use the Issue Tracker in future
