### ISSUE TITLE
Import Bestellungen aus Magento nicht vollständig

### ISSUE THREAD

**Issue by dpsgjacobs** [shopwareLabs/SwagMigration#4]
Beim Import von Magento 1.6.2 werden alle Artikel und Kunden korrekt importiert. Von den ca. 30.000 Bestellungen werden jedoch nur knapp über 1.000 importiert.
Eine Fehlermeldung gibt es nicht.

**Comment by dnoegel** [comment]
Danke, ich lege dafür ein Ticket an. Eigentlich sollten Tickets auf jira.shopware.de gepflegt werden, ich werde das hier gleich mal um-konfigurieren, nicht wundern :)
