### ISSUE TITLE
Bilder-Import funktioniert nicht bei lokalem Pfad

### ISSUE THREAD

**Issue by ftll** [shopwareLabs/SwagMigration#6]
Beispiel-Pfad: /var/www/ein-alter-shop

In ImageImporter.php verhindern die Zeilen 93-95, dass lokale Pfadangaben funktionieren:

```php
if (!strpos($image["image"], "http://") && !strpos($image["image"], "https://")) {
    $image["image"] = "http://" . $image["image"];
}
```

So wird aus /var/www/ein-alter-shop leider http:///var/www/ein-alter-shop

**Comment by mitelg** [comment]
Hi @ftll,
I just created a ticket for this in our issue tracker: https://issues.shopware.com/#/issues/PT-5132
you can follow this issue there 

Grettings
