### ISSUE TITLE
Uppercase SQL Statement

### ISSUE THREAD

**Issue by d3br0wn** [shopwareLabs/SwagMigration#7]
SwagMigration/Components/DbServices/Import/CustomerImporter.php - start at line 582

Uppercase can cause problems here:         

> $sql = 'DELETE FROM S_CAMPAIGNS_MAILADDRESSES
>                     WHERE EMAIL = ' . $customer['email'];
         

>  $sql = 'SELECT ID
>                     FROM S_CAMPAIGNS_MAILADDRESSES
>                     WHERE EMAIL = ' . $customer['email'];

**Comment by mitelg** [comment]
fixed with [53930570774](https://github.com/shopwareLabs/SwagMigration/commit/539305707743f07ee8e9a65d094f08f3f0412111)
