### ISSUE TITLE
Image import doesn't work when you follow the instructions

### ISSUE THREAD

**Issue by msslovi0** [shopwareLabs/SwagMigration#8]
The string in _articleImagesPath_ for importing images currently doesn't match the behavior of the image importer:
Shop path (e.g. http://www.example.org/shop or /var/www/oxid)

Suppling _http://cuc1.wstatic.com/_ as Shop path leads to:
`Copying image from 'http://http://cuc1.wstatic.com/images/product_images/highres_images/4032632100458_30-11-0310_1103-10.jpg' to '/var/www/media/temp/4032632100458_30-11-0310_1103-10' did not work!`

This is at least true for the xt:Commerce importer but might affect other importers as well.

**Comment by mitelg** [comment]
Hi @msslovi0,
we already have a ticket for the image import [PT-5132](https://issues.shopware.com/#/issues/PT-5132)
Maybe you could add a comment for your problem there. So we could close this issue here.
Greetings Michael
